uclaacm/acmcyber.com

pages/home.tsx
=> add homepage

.eslintrc.json, package.json, yarn.lock
=> eslint fixed syntax error check

components/Navbar.tsx, data/events.ts, pages/events.tsx, styles/Events.module.scss
=> add events toggle

package.json, pages/about.tsx, pages/index.tsx, yarn.lock
=> minor changes to prettier lint and fixed for about page

components/Navbar.tsx, styles/Navbar.module.scss
=> acm.cyber redirects to home

_data/officers.yml, components/Navbar.tsx, data/officers.yml, next.config.js, package.json, pages/blog.tsx
See title for changes. TODO: combine files in data folder to one type (will prob do .js). Please check if I fixed next.js. Thanks.
=> added blog page, combined data folders, next.js?

next.config.js, pages/events.tsx, styles/Events.module.scss
=> events css rooftops

pages/blog.tsx, styles/Blog.module.scss
=> made blog cards

data/blog/2023-01-02-firstpost.md, pages/blog/[id].tsx, styles/Post.module.scss, styles/globals.scss, utils/BlogPostData.tsx
=> added blog page scss

pages/blog.tsx, styles/Archiveitem.module.scss, styles/Blog.module.scss, styles/Home.module.scss, styles/globals.scss
Various cards had completely different styling
I used css vars to share color values. They can be changed later on if the design changes.
Note that homepage doesn't have the border. I didn't add the border bc those cards are not interactive but if it would look better y'all should add `border: var(--card-border);` to home card's style
=> Unify Card Styles

pages/_app.tsx, styles/globals.scss
=> Load fonts in production

styles/globals.scss
* use default typography principles from [Kevin Powell](https://www.youtube.com/user/KepowOb) to increase readability
=> Better Typography

.yarn/sdks/eslint/bin/eslint.js, .yarn/sdks/eslint/lib/api.js, .yarn/sdks/prettier/index.js, .yarn/sdks/typescript/lib/tsc.js, .yarn/sdks/typescript/lib/tsserver.js, .yarn/sdks/typescript/lib/tsserverlibrary.js, .yarn/sdks/typescript/lib/typescript.js, components/ArchiveItem.tsx, data/archive.ts, next.config.js, pages/blog.tsx, styles/Archiveitem.module.scss, styles/Navbar.module.scss, styles/Tag.module.scss, styles/globals.scss, utils/index.ts
=> archive stuff

pages/index.tsx
=> fix: swapped URLs for initiatives

pages/events.tsx
closes #76 
tldr: math for event belong to same week is incorrect, need to fix
=> [FIX] use @Aplet123 isSameWeek comparator

styles/Navbar.module.scss
=> [fix] Mobile Navbar

styles/Home.module.scss
=> feat: add background splash

components/Navbar.tsx
=> feat: automatically close navbar on navigation

pages/join.tsx
=> added membership form to join us page

data/archive.ts, data/events.ts
=> feat: archive fall gm slides + update Cyber Lab location

data/events.ts, pages/about.tsx
our code was too well written
actually suffering from success :skull:
=> remove special topics from /about

pages/join.tsx, styles/Join.module.scss
On `/join`, many members expressed confusion on where exactly the sign up form was to join the club. This feature adds a large button to try and make it clear where the form is.
=> feat(membership-form): added a clear join button on the `/join` page

pages/events.tsx, styles/Events.module.scss
Added Cyber Events Google Calendar invite link for easy access!
=> feat(gcal): added Google Calendar link to `/events`

pages/events.tsx
=> Fix calendar link to not have /u/3 in it

styles/Archive.module.scss, styles/Events.module.scss
For #142 
for some reason this doesnt work with `yarn build` and `yarn start` but it does with `yarn run dev`??
all i changed was some css but hopefully its ok it looks good when it works.
=> fixed archive card overflow overflow

data/members.ts, data/scripts/update_members.py
some of the transfer students told me that their information wasn't right on the website
=> fixed some member data

components/Navbar.tsx, pages/about.tsx, styles/Home.module.scss, styles/Navbar.module.scss, styles/globals.scss
do we wanna make the navbar buttons narrower or nah?
closes #160 
closes #111
=> the navbar overhaul

components/Footer.tsx, pages/index.tsx, styles/Footer.module.scss, styles/Home.module.scss
changes:
- an actually useful call to action (the second button actually links to `/join` but having a `Join Us` button feels too weird)
- removed the mailing list icon and replaced it with linkedin
- changed the other mailing list button to a github pages button
fixes #169
=> Update socials + our call to action

pages/join.tsx, styles/Join.module.scss
=> disable membership buttom + add styles + add discord buttom

pages/blog.tsx
Closes #175 
Moved blog filter selectors to new line.
=> Moved blog filters to new line

data/archive.ts
=> support summer events with `'u'` prefix

next.config.js, pages/discord.tsx, styles/Discord.module.scss
Closes #174 
Added /discord which redirects to ACM Cyber discord server
=> add discord redirect page

pages/discord.tsx
see above, previous discord invite link expired
=> fix /discord redirect to permanent discord invite

pages/join.tsx
=> Add membership form

data/members.ts
Update my member description to match others for now. Also modified Salma's.
=> Update Member Descriptions

styles/Post.module.scss, styles/globals.scss
would like a double-check that there aren't other weird styling things
changes:
- made lists indented
- links have color and underline
- made inline code blocks have a background (not sure if i'm using the right color though)
- added space around top/bottom of images, code blocks, and h3/h4
- increased line spacing to 1.5
Perhaps the h3/h4 elements need to be bigger but I'm not sure
=> fixed some styling for blog posts

pages/join.tsx
Disables membership requirements button to avoid confusion at the start of the quarter.
=> feat(membership-requirements): disable button for start of quarter

components/Footer.tsx
=> remove powered by github

styles/Blog.module.scss
- each row of blog post cards should also have the same height
#224
=> dynamically size height of blog posts
